#!/bin/sh -e

SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")
BUILD_FOLDER="build-analysis"

cd "$SCRIPT_PATH"/..

echo "Running Clang-tidy"
echo
cmake -S . -B "$BUILD_FOLDER" -DRUN_CLANG_TIDY=ON
echo
cmake --build "$BUILD_FOLDER" --target all -- -j $(($(nproc) / 2)) 2>&1 | tee clang-tidy-analysis.log
echo

rm -rf "$BUILD_FOLDER"

echo "Running CppCheck"
echo
cmake -S . -B "$BUILD_FOLDER" -DRUN_CPPCHECK=ON
echo
cmake --build "$BUILD_FOLDER" --target all -- -j $(($(nproc) / 2)) 2>&1 | tee cppcheck-analysis.log
echo

rm -rf "$BUILD_FOLDER"

echo "Running IWYU"
echo
cmake -S . -B "$BUILD_FOLDER" -DRUN_IWYU=ON
echo
cmake --build "$BUILD_FOLDER" --target all -- -j $(($(nproc) / 2)) 2>&1 | tee iwyu-analysis.log
echo

rm -rf "$BUILD_FOLDER"

echo "Running LWYU"
echo
cmake -S . -B "$BUILD_FOLDER" -DRUN_LWYU=ON
echo
cmake --build "$BUILD_FOLDER" --target all -- -j $(($(nproc) / 2)) 2>&1 | tee lwyu-analysis.log