#!/bin/sh -e

SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")
BUILD_FOLDER="build/tests"

cd "$SCRIPT_PATH"/..

cmake -S . -B "$BUILD_FOLDER" -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
echo
cmake --build "$BUILD_FOLDER" --target all -- -j $(($(nproc) / 2))
echo
cmake --build "$BUILD_FOLDER" --target test