#!/bin/sh -e

SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

cd "$SCRIPT_PATH"/..

cmake -S . -B build -DBUILD_TEST=ON
echo
cmake --build build --target all -- -j $(($(nproc) / 2))
echo
cmake --build build --target test